### PR TITLE
chore(semantic-release): update all packages to latest

### PR DESCRIPTION
**Pull request by ThomasClearC2**

### CODE REVIEW

**Comment by ThomasClearC2** [comment]
@dadamssg can you take a look at this? The dry-run seemed to work and I went ahead and bumped up the major version

**Comment by dadamssg** [comment]
i think you missed the point of this package haha.

You shouldn't be bumping the version number yourself. The semantic-release package will increase and cut releases to github based on the commit messages. Since you bumped this a major version you need to include a `BREAKING CHANGE` message in at least one of your commit messages. 

- If semantic-release see's a `feat` it will bump the package a minor version: `2.0.0` -> `2.1.0`.
- If it sees a `fix` it will bump the package's last digit: `2.1.0` -> `2.1.1`
- If it sees a `BREAKING CHANGE: <description of breaking change>` in a commit message body it will bump a major version regardless of commit type(feat, fix, etc): `2.1.1` -> `3.0.0`

What you need to do:
- revert the version number back to what it was
- `git add package.json`
- `yarn cm`

`yarn cm` will you run you through an interactive prompt to formulate a proper commit message. Pick `fix`. It will ask you if there are breaking changes, you press `y` and enter. You'll then be able to fill it out: "Bumping semantic-release a major version"

**Comment by ThomasClearC2** [comment]
That was pretty smooth, I will do the same for c2-react-config

**Pull request merged**
